language: node_js
dist: xenial
node_js:
  - 'stable'
cache: yarn
branches:
  except:
    - gh-pages
script:
  - yarn lint
  - yarn test --coverage
  - yarn build
  - yarn docs:build && cp .docz/dist/index.html .docz/dist/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .docz/dist
  on:
    branch: master
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
